#!/bin/sh
#
# run_test [1]
#
# James Bevins 1Jun2016

export CC=gcc
export CXX=g++
export FC=gfortran

#....choose linker based on availability of fortran compiler
which $FC > /dev/null && export LD=$FC || export LD=$CXX

export LD_LIBRARY_PATH=/home/pyne-user/FREYA_v1.9.1/lib
export DYLD_LIBRARY_PATH=${LD_LIBRARY_PATH} # MacOSX
export INCLUDE='-I/home/pyne-user/FREYA_v1.9.1/include'
export LIBS='-L/home/pyne-user/FREYA_v1.9.1/lib -lFission -lstdc++ -lm'
# export EXTRAFCFLAGS='-nofor_main'
export EXTRAFCFLAGS=''

#....process command line arguments (select which test to run)
if [ $# -eq 0 ]; then
    export test1=1
else
    export test$1=1
fi

#....compile and run the tests
if [ ! -z ${test1+x} ]; then
   which $FC > /dev/null || ( echo Need $FC to link FREYA test && exit )
   echo Compiling and linking U235t
   $CC  U235t.c -g -O3 -DFREYA -c $INCLUDE
   $LD  U235t.o -g -O3 -o U235t $EXTRAFCFLAGS $LIBS

   export FREYADATAPATH=/home/pyne-user/FREYA_v1.9.1/data_freya
   echo "set FREYADATAPATH=$FREYADATAPATH"
   echo "running U235t"
   if [ -f U235tSpec.res ]; then rm -f U235tSpec.res; fi
   if [ -f U235tSpecTotal.res ]; then rm -f U235tSpecTotal.res; fi
   if [ -f U235tTotal.res ]; then rm -f U235tTotal.res; fi
   time ./U235t
   echo
fi
