SCALE Job started on Mon 05/03/2018 19:39:19
With Host name NICK
working directory C:\Users\nickq\AppData\Local\Temp\scale.nickq.17748
and process id 17748.
Input file named C:\Users\nickq\Documents\AFIT_Masters\NIF_ETA\Scale\Examples\monaco.howitzer.inp
and output file named C:\Users\nickq\Documents\AFIT_Masters\NIF_ETA\Scale\Examples\monaco.howitzer.out
##########################################################
***Created 3 infinite homogeneous cells from unreferenced mixtures.
***Warning: Nuclide 8018 is missing cross sections. Introducing zero cross sections.
  Now executing monaco.exe                      
 Monaco has started.
     call newUserInput()
     call loadTheGame
         call loadUserInput
         call checkUserInput
         call checkUserInput2
         call checkUserInput3
         call checkUserInput4
         call crossSectionMaker
              crossSectionMaker done
     call playTheGame
         point detector tallies
         region tallies
         mesh tallies
         mesh moment tallies



 Starting the Monte Carlo game with 8650005740006085

 Monaco/MAVRIC Training - Exercise Problem 1.  Neutron Howitzer              

     batch    batches        batch time   elapsed time      next randomSeed
     ----------------     -------------  -------------     ----------------
